// # Numbers
// 1. Assign by hand same value to 3 variables in binary, octal and hexadecimal format.

const binary = 0b11100100;
console.log(binary);

const octal = 0o344;
console.log(octal);

const hex = 0xE4;
console.log(hex);

// 2. Implement function `extractNumbers` which will leave only numbers in passed string.

function extractNumbers (text) {
  const checkInt = parseFloat(text);
  if (isNaN(checkInt)) {
    return null;
  }
  if (typeof checkInt === 'number') {
    return true;
  }
}

const valueExample = '23test';
console.log(extractNumbers(valueExample));

// 3. Declare a variable with decimal value and convert to binary, octal and hexadecimal.

const someDecimalNumber = 130;
const binaryFromDecimal = someDecimalNumber.toString(2);
console.log(binaryFromDecimal);

const octalFromDecimal = someDecimalNumber.toString(8);
console.log(octalFromDecimal);

const hexFromDecimal = someDecimalNumber.toString(16);
console.log(hexFromDecimal);

// 4. use `Math.random` to generate random value from `0` to `100`.

function randomNumber(min, max) {
  return min + Math.floor(Math.random() * (max - min + 1));
}

const roundedRandomDecimal = Math.round(randomNumber(1, 100));
console.log(roundedRandomDecimal);

// # Additional
// 1. Make function which will take a array with numbers as a parameter and
// calculate average number and round to hundredths.
// 2. Generate array to pass to function above with values, and length generated by Math.random.

function averageNumberFromArray(array) {
  let summary = 0;
  array.forEach((arrayItem) => {
    summary += parseInt(arrayItem, 16);
  });
  return (summary/array.length).toFixed(3);
}

const arrayForCalc = [];
for (let i = 0; i <= randomNumber(0, 10); i++) {
  let hexNumber = randomNumber(100, 200).toString(16);
  arrayForCalc.push(hexNumber);
}

console.log(averageNumberFromArray(arrayForCalc));
